### ISSUE TITLE
Problema al configurar la ultima version de libredte community

### ISSUE THREAD

**Issue by yieniggu** [sascocl/sowerphp#11]
Hola, estamos intentando actualizar a la ultima versión (ya que la documentación de la 21.10 no existe más) y estamos teniendo el siguiente problema? Nos podrian dar una ayuda con esto. Muchas gracias de antemano:

![image](https://github.com/sascocl/sowerphp/assets/45997136/05bd8922-a4fd-4af6-ab13-eb04d97bb6b0)

**Comment by estebandelaf** [comment]
Hola, si quieres usar la versión 21.10 es esta:

https://github.com/sascocl/sowerphp/releases/tag/21.10.0

**Comment by yieniggu** [comment]
Hola, al intentar instalar esa versión tenemos problemas con los paquetes 

```
"lapinator.net/ods-php-generator"
"elevenpaths/latch-sdk-php"
```

ya que al parecer en la instalación apuntan a repositorios de sasco que no existen. Tienen alguna documentación que podamos revisar para la ultima versión o en su defecto la 21.10? Gracias de antemano
